classDiagram
    namespace client {
        class Client {

        }
    }

    namespace internalcrm {
        class InternalCRMService {
            +findLeads(double lowAnnualRevenue, double highAnnualRevenue, String state) List~InternalLeadDto~
            +findLeadsByDate(Calendar startDate, Calendar endDate) List~InternalLeadDto~
            +deleteLead(InternalDto lead) void
            +addLead(InternalDto lead) void
        }

        class ModelITO {
            -String firstName
            -String lastName
            -double annualRevenue
            -String phone
            -String street
            -String postalCode
            -String city
            -String country
            -Calendar creationDate
            -String company
            -String state
        }

        class InternalLeadDto
    }

    namespace virtualcrm {
        class VirtualCRMService {
            +findLeads(double lowAnnualRevenue, double highAnnualRevenue, String state) List~VirutalLeadDto~
            +findLeadsByDate(Calendar startDate, Calendar endDate) List~VirutalLeadDto~
        }

        class VirtualLeadDto {
            -String firstName
            -String lastName
            -double annualRevenue
            -String phone
            -String street
            -String postalCode
            -String city
            -String country
            -Calendar creationDate
            -GeographicPointTO geographicPointTO
            -String company
            -String state
        }

        class GeographicPointDto {
            -double latitude
            -double longitude
        }
    }
